### ISSUE TITLE
".jirash.json" should be created with mode 0600

### ISSUE THREAD

**Issue by jclulow** [trentm/jirash#25]
I used the interactive setup for `jirash`, and it created a file in my home directory:

```
jclulow@jmcbook ~ $ ls -lh ~/.jirash.json
-rw-r--r--  1 jclulow  staff   153B Jun 18 13:51 /Users/jclulow/.jirash.json
```

It would be best, seeing as this file contains sensitive information, if it was created with mode `0600`.

**Comment by trentm** [comment]
Hi Josh.

jirash v2 (first released 2017-11-10) was re-written in node.js. This issue is for jirash v1, which is no longer supported so I'm closing this as "won't fix".  FWIW jirash v2 dropped the interactive setup of the config file ... for a lazy mention in the readme that one must first create the config file.

**Comment by jclulow** [comment]
Hey! :D

Makes sense!
